name: Deploy Angular Frontend

on:
  push:
    paths:
      - 'client/**'
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install & Build Angular
      run: |
        cd client
        npm install
        npm run build -- --output-path=dist

    - name: SonarCloud Scan
      uses: sonarsource/sonarqube-scan-action@master
      with:
        projectBaseDir: client
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: "https://sonarcloud.io"

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Angular to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: secure-frontend-app
        package: ./client/dist
